name: challenge one workflow
on: 
    push:
        branches:
            -   main
jobs: 
    job1:
        name: first job
        runs-on: ubuntu-latest
        steps: 
            -   name: print date step
                run: "date +\"%Y-%m-%d %H-%M-%S.%6N\""
    job2:
        name: second job
        runs-on: windows-latest
        steps: 
            -   name: print date step
                run: "(Get-Date).ToString(\"yyyy-MM-dd HH-mm-ss.ffffff\")"
    job3:
        name: third job
        runs-on: macos-latest
        steps:
            -   name: print date step
                run: "python3 -c 'from datetime import datetime; print(datetime.now().strftime(\"%Y-%m-%d %H:%M:%S.%f\"))'"
    job4:
        name: dependant job
        runs-on: ubuntu-latest
        needs: [job1,job2,job3]
        steps:
            -   name: print date
                run: "date +\"%Y-%m-%d %H-%M-%S.%6N\""
