name: challenge three workflow
on: 
    push:
        branches:
            # -   main #uncomment to run workflow
            -   challenge_three # so we don't bog down main when merged
jobs: 
    test:
        runs-on: ubuntu-latest
        steps: 
            -   uses: actions/checkout@v2
            -   run: |
                    cd challenge_three/
                    python helloworld.py

    build:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/upload-artifact@v4
                with:
                    name: challenge_three
                    path: ./challenge_three