name: challenge three workflow
on: 
    push:
        branches:
            # -   main #uncomment to run workflow
            -   challenge_three # so we don't bog down main when merged
jobs: 
    test:
        name: test
        runs-on: ubuntu-latest
        steps: 
            -   name: checkout
                uses: actions/checkout@v2

            -   name: test                
                run: |
                    cd challenge_three/
                    python helloworld.py

    build:
        name: build
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            -   name: checkout
                uses: actions/checkout@v2

            -   name: upload artifact step
                uses: actions/upload-artifact@v4
                with:
                    name: challenge_three
                    path: ./challenge_three