name: myworkflow
on: push
env:
    MY_WORKSPACE_ENVIRONMENT_VARIABLE: 'WS env value'
jobs: 
    job1:
        name: ubuntu job
        runs-on: ubuntu-latest
        steps: 
            -   name: step one
                uses: actions/checkout@v2
            -   name: step two
                env:
                    MY_STEP_ENVIRONMENT_VARIABLE: 'Step env value'
                run: |
                    echo "Access env variable using shell syntax"
                    echo "1. $MY_WORKSPACE_ENVIRONMENT_VARIABLE"
                    echo "2. $MY_STEP_ENVIRONMENT_VARIABLE"
                    echo "---"
                    echo "Access env variable using shell syntax"
                    echo "5. ${{env.MY_WORKSPACE_ENVIRONMENT_VARIABLE}}"
                    echo "6. ${{env.MY_STEP_ENVIRONMENT_VARIABLE}}"
                    echo "Secrets"
                    echo "7. ${{secrets.MY_SECRET}}"
    job2:
        name: windows job
        runs-on: windows-latest
        steps:  
            -   name: step one
                uses: actions/checkout@v2
            -   name: step two
                run: "Get-ChildItem Env: | Sort-Object Name"