name: myworkflow
on: push
env:
    MY_WORKSPACE_ENVIRONMENT_VARIABLE: 'WS env value'
jobs: 
    job1:
        name: ubuntu job
        runs-on: ubuntu-latest
        outputs:
            artifact-name: env-file
        steps: 
            # -   name: step one
            #     uses: actions/checkout@v2
            -   name: show my env variables
                env:
                    MY_STEP_ENVIRONMENT_VARIABLE: 'Step env value'
                run: |
                    echo "Access env variable using shell syntax"
                    echo "1. $MY_WORKSPACE_ENVIRONMENT_VARIABLE"
                    echo "2. $MY_STEP_ENVIRONMENT_VARIABLE"
                    echo "---"
                    echo "Access env variable using shell syntax"
                    echo "5. ${{env.MY_WORKSPACE_ENVIRONMENT_VARIABLE}}"
                    echo "6. ${{env.MY_STEP_ENVIRONMENT_VARIABLE}}"
                    echo "Secrets"
                    echo "7. ${{secrets.MY_SECRET}}"

            -   name: create env file artifact step
                run: |
                    echo "job 1 env variables" > env-file.txt
                    env >> env-file.txt

            -   name: upload artifact step
                uses: actions/upload-artifact@v3
                with:
                    name: env-file
                    path: ./env-file.txt

    job2:
        name: windows job
        runs-on: windows-latest
        needs: job1
        steps:  
            -   name: show job2 env variables step
                run: "Get-ChildItem Env: | Sort-Object Name" 

            -   name: download artifact
                uses: actions/download-artifact@v3
                with:
                    name: env-file
                
            -   name: show job1 env variables from artifact step
                run: cat ./env-file.txt

